fonts & index
anchoislala/team-project-IceCream pull request #4
Opened 2022-01-14 21:29 UTC by mihail228350df

2022-01-15 10:03 UTC, anchoislala commented on src/sass/utils/_visually-hidden.scss
> +.is-hidden{
такой файл уже существует в sass

2022-01-15 13:32 UTC, anchoislala requested changes

2022-01-15 13:32 UTC, anchoislala commented on src/sass/utils/_variables.scss
> +//--------------Fonts-------------------//
такой файл уже существует в sass

2022-01-15 13:32 UTC, anchoislala commented on src/sass/utils/_reset.scss
> +h1,
такой файл уже существует в sass

2022-01-15 13:32 UTC, anchoislala commented on src/partials/index.html
> +<!DOCTYPE html>
В папке partials мы кладем только "части" нашего главного index.html, который лежит уже в папке src, изменения вносим в него

2022-01-15 13:32 UTC, anchoislala commented on src/sass/layouts/_advantages.scss
> +.visually-hidden {
visually-hidden уже у нас добавлен, здесть его вписывать не нужно

2022-01-15 13:32 UTC, anchoislala commented on src/js/mobile-menu.js
> +(() => {
часть Mobile/Modal menu приписана к Семену

2022-01-15 13:32 UTC, anchoislala commented on src/partials/advantages.html
> +        <h2 class="advantages_visually-hidden visualli-hidden">Advantages!</h2>
<h2 class="advantages_visually-hidden visualli-hidden"> -> <h2 class="advantages_visually-hidden visually-hidden">

2022-01-15 13:32 UTC, anchoislala commented on src/sass/layouts/_advantages.scss
> +.backdrop.is-hidden {
backdrop думаю лучше положить в файл с модалкой

2022-01-15 13:32 UTC, anchoislala commented on src/sass/utils/_main.scss
> +@import "mixins";
здесь оставить только mixins, если большинство проголосуют

2022-01-15 13:32 UTC, anchoislala commented on src/sass/main.scss
> +@import "/.layouts/main";
components и layouts где эти файлы?

2022-01-16 07:34 UTC, mihail228350df commented on src/sass/utils/_main.scss
> +@import "mixins";
думаю надо так все и оставить

2022-01-16 22:08 UTC, anchoislala requested changes

2022-01-16 22:08 UTC, anchoislala commented on src/sass/layouts/_main.scss
> +@import "hero-header";
этот файл удалить, каждый уже вписал свою секцию, допиши только import своей в файле main.scss

2022-01-16 22:08 UTC, anchoislala commented on src/sass/utils/_main.scss
> +@import "mixins";
оставляем только миксины, потому что остальные файлы уже существуют, миксины подключить в main.scss

2022-01-16 22:08 UTC, anchoislala commented on src/sass/components/_container.scss
> +.container {
этот файл удалить, потому что он уже существует

2022-01-16 22:08 UTC, anchoislala commented on src/sass/components/_buttons.scss
> +%button {
этот файл удалить, потому что он уже существует

2022-01-16 22:08 UTC, anchoislala commented on src/sass/components/_base.scss
> +body {
этот файл удалить, потому что он уже существует

2022-01-16 22:08 UTC, anchoislala commented on src/sass/components/_main.scss
> +@import "base";
этот файл удалить

2022-01-16 22:08 UTC, anchoislala commented on src/partials/advantages.html
> +<section class="advantages" id="section-advantages">
id здесь не нужен -  id="section-advantages"

2022-01-16 22:08 UTC, anchoislala commented on src/sass/components/_modal.scss
> +backdrop {
модалки делает Семен, договоритесь кто должен добавить этот файл

2022-01-17 11:00 UTC, mihail228350df commented on src/js/mobile-menu.js
> +(() => {
почему только часть пускай забирает все

2022-01-17 11:12 UTC, mihail228350df commented on src/partials/advantages.html
> +        <h2 class="advantages_visually-hidden visualli-hidden">Advantages!</h2>
изминил

2022-01-17 11:15 UTC, mihail228350df commented on src/partials/advantages.html
> +<section class="advantages" id="section-advantages">
изминил

2022-01-17 14:16 UTC, anchoislala approved these changes

2022-01-17 14:19 UTC, merged