Feature/header
anchoislala/team-project-IceCream pull request #8
Opened 2022-01-15 23:48 UTC by IrynaKozhukh

начальная мобильная версия хедер и хироу. проблемка с подключением картинок и бургер-иконки. прошу помощи у Андрея

2022-01-16 18:46 UTC, anchoislala requested changes

2022-01-16 18:46 UTC, anchoislala commented on src/partials/header.html
> +
не хватает одного `/div`

2022-01-16 18:46 UTC, anchoislala commented on src/sass/_header.scss
> +a {
это уже есть в файле _reset.scss

2022-01-16 18:46 UTC, anchoislala commented on src/sass/_header.scss
> +img {
это уже есть в файле _reset.scss

2022-01-16 18:46 UTC, anchoislala commented on src/sass/_header.scss
> +button {
это мне кажется лучше положить в папку sass/utils/_reset.scss

2022-01-16 18:46 UTC, anchoislala commented on src/sass/_header.scss
> +.container {
это уже есть в файле components/_container.scss

2022-01-16 18:46 UTC, anchoislala commented on src/sass/_header.scss
> +.button {
общие стили для класса `button` есть в файле sass/components/_button.scss
если нужно перебить для себя, то добавить класс+модификатор

2022-01-16 21:53 UTC, IrynaKozhukh commented on src/sass/_header.scss
> +button {
fixed

2022-01-16 21:54 UTC, IrynaKozhukh commented on src/sass/_header.scss
> +img {
удалила

2022-01-16 21:54 UTC, IrynaKozhukh commented on src/sass/_header.scss
> +.container {
удалила

2022-01-16 21:54 UTC, IrynaKozhukh commented on src/sass/_header.scss
> +.button {
хорошо

2022-01-16 21:55 UTC, IrynaKozhukh commented on src/sass/_header.scss
> +a {
удалила у себя

2022-01-16 21:55 UTC, IrynaKozhukh commented on src/partials/header.html
> +
добавила

2022-01-17 07:21 UTC, anchoislala approved these changes

2022-01-17 07:56 UTC, merged